### ISSUE TITLE
Typo in odsChartSerie documentation: "label-y" vs. "labelY"

### ISSUE THREAD

**Issue by jb3-2** [opendatasoft/ods-widgets#126]
Hi, I think I found a typo in this page: https://help.opendatasoft.com/widgets/#/api/ods-widgets.directive:odsChartSerie

Here it says "label-y": 
![image](https://user-images.githubusercontent.com/7261044/81798041-d5aaa580-950f-11ea-9b8a-79a008d10ec5.png)

...and further down it says "labelY": 
![image](https://user-images.githubusercontent.com/7261044/81798117-f115b080-950f-11ea-8db7-0c88174c9e12.png)

I think "label-y" is correct. I don't understand where I can change that in your source code so I could not create a pull request directly, sorry.

**Comment by richterb** [comment]
Hello,

Parameters are indeed written in different cases depending on the situation. This is a convention introduced by the official AngularJS documentation (for example https://docs.angularjs.org/api/ng/input/input%5Btext%5D), because one parameter's case is modified by AngularJS itself depending on the context (because HTML attribute, HTML elements, JavaScript variables all have different contraints, so the attribute `label-y` becomes `labelY` inside the JS code for example). We decided to use the same convention so that our documentation is more consistent with the AngularJS one, as you often have to use built-in AngularJS directives together with ODS-Widgets directives (`ng-if` ...).

We've described how the parameters are documented here: https://help.opendatasoft.com/widgets/#/getting-started/01widgetdoc
