### ISSUE TITLE
Adding Select options to context?

### ISSUE THREAD

**Issue by kachroudi-Nedra** [opendatasoft/ods-widgets#93]
Hi,

How can i add action from Select to context ? i did this but it does'nt work.

`<select name="singleSelect" ng-init="option-1" ng-model="singleSelect">
      <option value="option-1">Option 1</option>
      <option value="option-2">Option 2</option>
    </select>`

          <ods-dataset-context  context="context" context-dataset="mycontext" contextparameters="{'refine.origin':singleSelect}" >

Thanks

**Comment by kachroudi-Nedra** [comment]
The select options: 
 <select name="singleSelect" ng-init="option-1" ng-model="singleSelect">
      <option value="option-1">Option-1</option>
      <option value="option-2">Option 2</option>
    </select>

**Comment by jmorel** [comment]
Hi,

Two things seem to be missing: the ng-init isn't set properly ``option-1`` instead of ``singleSelect=option-1`` and the dash between context and parameters.

Also, while it may not be an issue, you should avoid naming your context "context". If you absolutely want a generic name, ctx would be better suited. Also it seems you named your dataset "mycontext". Are you sure this is the right dataset id ?

Here is a sample code that should work.

```html
<select name="singleSelect" ng-init="singleSelect='option-1'" ng-model="singleSelect"> <option value="option-1">Option-1</option> <option value="option-2">Option 2</option> </select>
<ods-dataset-context  context="ctx" ctx-dataset="my-dataset-id" ctx-parameters="{'refine.myfacetname':singleSelect}" ></ods-dataset-context>


```

**Comment by kachroudi-Nedra** [comment]
Thanks for your reply, 

Your code works on init, but when  i select value,the context doesn't change for the value selected.
 how can i do add action change from <select> to the context?

and if add `ng-change="action" what action i put? `

Thanks

**Comment by fpassaniti** [comment]
Hi, 

Please have a look to it's sample in our cookbook, it should do what you want, ie an html select with auto refine and change refine parameter dynamically

https://github.com/opendatasoft/ods-cookbook/tree/master/widgets/facet-as-a-list-selection
