### ISSUE TITLE
Using odsFacetResult with an odsTextSearch

### ISSUE THREAD

**Issue by itkg-asepchat** [opendatasoft/ods-widgets#99]
Hello ! 

I need to combine a research with an odsTextSearch input, and an odsFacetResult widget.
My form is : Input Text Search + 4 combolist, I need to submit all that research criteres in the same time.
Is someone able to help me about it ?
I'm really in front of a wall..
Thanks in advance !

**Comment by richterb** [comment]
Hello,

If I understand correctly, the big issue here is to be able to apply the search when the button is clicked, instead of updating the result each time something is clicked?

I can think of a somewhat ugly solution which would be to have two contexts; a first one just used to "store" the parameters (so plugged to the odsTextSearch widgets and the combolist), and a second one used by the odsFacetResult widget. The search button would copy all the parameters from one context to the others when clicked, with something like `ng-click="context2.parameters = context1.parameters"

Hope this helps.
